### ISSUE TITLE
Feature Request - Use of multiple world seeds. Biome/Cave/World Height

### ISSUE THREAD

**Issue by Tabletopcheese** [pl3xgaming/PurpurDocs#26]
Not sure if this is entirely possible, but I thought it would be interesting.

![image](https://user-images.githubusercontent.com/14104281/144098970-322030b4-bb8b-4c96-be96-08f5f5663564.png)

video on it

https://www.youtube.com/watch?v=BbGUHAUfpv4

**Comment by Tabletopcheese** [comment]
Saw purpur already had some custom seed values, so I was curious if it just wasnt possible for the other seed values.

**Comment by BillyGalbreath** [comment]
Yup, we had this [feature for a long time](https://purpur.pl3x.net/docs/Configuration/#feature). But recently Paper adopted it, so we dropped ours to prevent duplicate configs. We just haven't updated our docs to remove the feature seeds yet.

Paper's feature seeds settings: https://paper.readthedocs.io/en/latest/server/configuration.html#feature-seeds

Spigot's structure seed settings: https://www.spigotmc.org/wiki/spigot-configuration/ (look for settings like `seed-village`, etc)

The only ones we still include in Purpur are the 3 structure seeds Paper and Spigot do not include

https://purpur.pl3x.net/docs/Configuration/#structure

**Comment by Tabletopcheese** [comment]
Oh man. Thank you for the kind and educational reply. I really felt I was missing something. 

It looks like I still have a lot to read up on.

This followup is obviously out of scope, so only if you know off the top of your head
Does this also work for the decorators?, which one these is just the locations the biomes are mapped?

Ive only learned about this last night, and am still very confused, but want to try some stuff out.

**Comment by BillyGalbreath** [comment]
AFAIK, yes. I believe there's a lot of naming ambiguity when its comes to these things (but I may be wrong).

Structures are the underlying "foundation" for chunk features used in what mojang calls jigsaw. https://minecraft.fandom.com/wiki/Configured_structure_feature

Features, decorators, and populators are all terms I've seen used for the same thing, which is the more intricate pieces of structures, or sometimes they stand alone without structures. https://minecraft.fandom.com/wiki/Configured_feature
